feat(*) docker hub transition
Kong/kong-pongo pull request #176
Opened 2021-05-27 15:24 UTC by aboudreault

* Bintray removal
* Docker hub transition:
  * OSS: no change
  * Entreprise images: it tries to fetch using the repo `kong/kong-gateway`. If not found, fallback to `kong/kong-gateway-private`.
  * Nightly EE: it tries to fetch using the repo `kong/kong-gateway-internal`.

Env vars required for the Enterprise license:
* PULP_USERNAME
* PULP_PASSWORD

Env vars required for most of enterprise and nightly images :
* DOCKER_USERNAME
* DOCKER_PASSWORD

TODO:
* wait the merge required for the nightly 2.4 image to test `nightly-ee`

2021-05-27 15:25 UTC, aboudreault commented on README.md
> +- `DOCKER_PASSWORD=<your_docker_password>`
I prefer to use _DOCKER_*_, but I'm OK if we prefer to use NIGHTLY_EE_*, if widely used across repositories.

2021-05-27 15:26 UTC, aboudreault commented on .travis.yml
> +  - PULP_USERNAME=admin
this can be confusing, but the admin user is just a user with read/write permissions, it can't delete artifacts. I validated with devops that it's OK to use in CI.

2021-05-27 16:11 UTC, mikefero requested changes

2021-05-27 16:11 UTC, mikefero commented on pongo.sh
> +        docker_login
Not for this PR, but I wonder if in the future Pongo should perform the `docker login` if the credentials are present and then `docker logout` after Pongo completes execution of the `docker pull`. This would allow for increased `docker pull` rate-limiting using certain docker user accounts.

This would work for both OSS and Enterprise docker pulls.

2021-05-27 16:11 UTC, mikefero commented on pongo.sh
> +  NIGHTLY_EE_TAG="kong/kong-gateway-internal:next-2.4.x.x-nightly-alpine"
Based on the branching strategy we should make this point to the `master` nightly instead.

```suggestion
  NIGHTLY_EE_TAG="kong/kong-gateway-internal:master-nightly-alpine"
```

2021-05-27 16:16 UTC, aboudreault commented on pongo.sh
> +        docker_login
Good point. I will create a ticket for this before the merge.

2021-05-27 18:04 UTC, Tieske commented
I had a wishlist for this, which needs to do more than just docker hub, lemme try and post it here

2021-05-27 18:10 UTC, Tieske commented
Pongo tests against Alpine based images

The following Kong images should be supported:

1. Released versions of CE
2. Released versions of EE
3. Development images CE
4. Development images EE
5. Custom images (released versions, modified by customers)

Issues to solve when building the test image:
1. how to specify the image/version
2. fetching the image
3. detecting the Kong versions to match with the proper dev files
4. name the built image


```
    | specify                      | fetch                               | detect             | name
----+------------------------------+-------------------------------------+--------------------+------
CE  | KONG_VERSION=x.y.z           | pull image, on failure login, retry | from KONG_VERSION  | ?
EE  | KONG_VERSION=x.y.z.a         | pull image, on failure login, retry | from KONG_VERSION  | ?
dCE | KONG_VERSION=<prefix>x.y.z   | login, pull image                   | tag with commit-id | ?
dEE | KONG_VERSION=<prefix>x.y.z.a | login, pull image                   | tag with commit-id | ?
cust| KONG_IMAGE=img-name          | image must be local                 | run "kong version" | ?
```
docker login: https://kongstrong.slack.com/archives/G01DLJCCP98/p1621426420000300

Credentials:
============

for generic access and bypassing rate-limits. No repo to be set since it is the
public docker hub. Used from BUILD and RUN commands.

 - DOCKERHUB_PUBLIC_USER=
 - DOCKERHUB_PUBLIC_SECRET=
 - DOCKERHUB_PUBLIC_REPO="docker.io"
 - DOCKERHUB_PUBLIC_TAG_PREFIX="kong:"
 - DOCKERHUB_PUBLIC_TAG_POSTFIX="-alpine"
 /* fallback used when published images are not yet available, to use unofficial ones */
 - DOCKERHUB_PUBLIC_TAG_FALLBACK_PREFIX="kong:"
 - DOCKERHUB_PUBLIC_TAG_FALLBACK_POSTFIX="-alpine"

for private EE images (released, older images). No repo to be set since it is the
public docker hub. Used for BUILD commands only.
NOTE: logging in with this, logs out with the public credentials (so on RUN, after the build login again with public creds to pull Postgres/Cassandra and other deps)

 - DOCKERHUB_PRIVATE_USER=
 - DOCKERHUB_PRIVATE_SECRET=
 - DOCKERHUB_PRIVATE_REPO=docker.io
 - DOCKERHUB_PRIVATE_TAG_PREFIX="kong/kong-gateway:"
 - DOCKERHUB_PRIVATE_TAG_POSTFIX="-alpine"



CE & EE
=======
CE versions are public on docker hub;

    docker pull kong:2.4.1-alpine

EE versions are public on docker hub;

    docker pull kong/kong-gateway:2.4.1.0-alpine

NOTE: older EE versions are NOT public;

    echo "$TOKEN" | docker login -u "username" --password-stdin
    docker pull kong/kong-gateway-private:0.36-2-alpine

Build CE:
1. login to public
2. pull
3. if failed pull on fallback
4. build

Build EE:
1. login to public
2. pull
3. if failed login to private and pull again
4. if logged into private, log out again
5. build

The login covers non-public EE versions, as well as the docker-hub rate-limit for
public images.

dev
===
Probably the same as CE & EE?
Requires docker repo for non-public EE versions to be the same as the dev-images

cust
====
In this case the image is expected to be available locally, no pulling is done?


KONG_VERSION vs KONG_IMAGE
==========================
KONG_VERSION is used to construct KONG_IMAGE.

2021-05-27 18:21 UTC, Tieske commented on README.md
> +  to allow Pongo to download the license file automatically.
Is the license file available in Pulp? I was told it was only available as a SalesForce portal download?

2021-05-27 18:21 UTC, Tieske commented on README.md
> +- `DOCKER_PASSWORD=<your_docker_password>`
NIGHTLY_EE should be replaced with a way to run individual development branches for supported versions

2021-05-27 18:21 UTC, Tieske commented on pongo.sh
> +  KONG_LICENSE_URL="https://download.konghq.com/internal/kong-gateway/license.json"
is this always named like this? previously the old license files would remain, and new licenses would get a different name.

My 2cts;
 - each file gets uploaded with a specific template, eg: `kong-license-<date>.json` that is retained
 - latest version is always available as `kong-license.json`

Note: `kong-` prefix, since we also have Kuma licenses

2021-05-27 18:21 UTC, Tieske commented on pongo.sh
> +    err "Failed to log into the nightly Kong Enterprise docker repo. Make sure to provide the
shouldn't this be a warning? public images will work without credentials right?

2021-05-27 18:21 UTC, Tieske commented on pongo.sh
> +        docker_login
if given we should log in, if not given we should try without. If it fails, we should retry with the private creds for EE images not publicly available (eg. `036-2` and the likes).

2021-05-27 18:51 UTC, mikefero commented on README.md
> +  to allow Pongo to download the license file automatically.
There will be yes. @aboudreault worked on the bits to access a rotating license similar to how things were done on Bintray. The goal is to keep everything in Pongo the same just pointing to different/newer locations.

2021-05-27 18:56 UTC, mikefero commented on pongo.sh
> +  KONG_LICENSE_URL="https://download.konghq.com/internal/kong-gateway/license.json"
>is this always named like this? previously the old license files would remain, and new licenses would get a different name.
>My 2cts;
>each file gets uploaded with a specific template, eg: kong-license-<date>.json that is retained
latest version is always available as kong-license.json

Unfortunately Pulp does not operate the same as Bintray. There is a notion of versions within pulp, but they are not accessible the same way. We will be able, through the API, to rollback/delete versions if needed, but when a file is change Pulp uploads will automatically increment the version for us so there is no need to add the granularity of a date to this and simply rotate the license regularly.

> Note: kong- prefix, since we also have Kuma licenses

The repo is `kong-gateway` on Pulp so when `Kuma` comes into play we will be able to create a `Kuma` repository.

2021-05-27 18:58 UTC, mikefero commented on pongo.sh
> +    err "Failed to log into the nightly Kong Enterprise docker repo. Make sure to provide the
Based on where the `docker_login` [is called](https://github.com/Kong/kong-pongo/pull/176/files#diff-c8f47a560d71fbab0fd0f0dfb4166fa999fa620ce079d78511634aa9f517afebR425) this should definitely be an error. When docker login is added in future work it should then be changed to a warning and then elevated to error only if the private images cannot be accessed due to failure to login.

2021-05-27 19:04 UTC, mikefero commented on README.md
> +- `DOCKER_PASSWORD=<your_docker_password>`
Confused here. These changes cover the switch from Bintray to Docker Hub and are not related to `NIGHTLY_EE_TAG`.

2021-05-27 19:20 UTC, mikefero commented
> I had a wishlist for this, which needs to do more than just docker hub, lemme try and post it here
> Pongo tests against Alpine based images
> 
> The following Kong images should be supported:
> 
> 1. Released versions of CE
> 2. Released versions of EE
> 3. Development images CE
> 4. Development images EE
> 5. Custom images (released versions, modified by customers)

1 - 4 should already be addressed with this transition as nightlies for each development branch of the Kong Gateway are now available (well the merges for the nightlies are slowly cascading their way through currently).

**Note**: The tagging convention for nightlies is `next-2.4.x.x-nightly-alpine` or the alias `2.4-nightly`; the same goes for other active branches with the exceptions being `master` (e.g. `master-nightly-alpine` => `master-nightly`) and 1.5.0.x (e.g. `next-1.5.0.x-nightly-alpine` => `1.5-nightly`)

> docker login: https://kongstrong.slack.com/archives/G01DLJCCP98/p1621426420000300

Not able to hit the link (might be a closed Slack channel)


All the other ideas seems like great enhancements for sure.

2021-05-27 20:01 UTC, aboudreault commented
@Tieske Can you create an issue with your wishlist? Your points seem to be good improvements, but will need to be worked on depending on the team priorities.

2021-05-28 03:51 UTC, Tieske commented on pongo.sh
> +  KONG_LICENSE_URL="https://download.konghq.com/internal/kong-gateway/license.json"
ok, cool. The underlying problem was that the old ways (bintray) had no way of deterministically fetching the latest license file. But I get that with Pulp we do have that, since it internally versions the files.

2021-05-28 04:56 UTC, Tieske commented on pongo.sh
> +  KONG_LICENSE_URL="https://download.konghq.com/internal/kong-gateway/license.json"
the url contains `/internal/` is that correct? looks like its a Kong internal url, what would the same url for a customer look like?

2021-05-28 05:04 UTC, Tieske commented on pongo.sh
> +  KONG_EE_PRIVATE_TAG_FALLBACK_POSTFIX="-alpine"
Not sure this is correct? `kong/kong-gateway-private` is the repo for non-public Enterprise images, eg. `0.36-2`.

The `FALLBACK` however is the location of "unofficial" images for CE. This means that when we publish a new versions, Docker takes some time (several days) to review our docker files and upload the official Kong image. Meanwhile our CI is failing since we added the version, but it isn't yet available. This is where the fallback kicks in, if a public CE version is unavailable we retry with the "unofficial" image, which is controlled by us and released at the same time as the other packages.

This whole problem does not exist for EE afaik, so this should not be FALLBACK.

2021-05-28 12:07 UTC, aboudreault commented on pongo.sh
> +  KONG_LICENSE_URL="https://download.konghq.com/internal/kong-gateway/license.json"
yes. as mentioned in the slack discussion, the customers have to set their KONG_LICENSE_DATA

2021-05-28 12:11 UTC, mikefero commented on pongo.sh
> +  KONG_LICENSE_URL="https://download.konghq.com/internal/kong-gateway/license.json"
Customers will be required to use the `KONG_LICENSE_DATA` variable since all the customer license information has been moved to the SalesForce portal. This license location will be for internal use only and allow us to have less changes throughout the multiple repositories where a plugin (or application) requires a Kong Gateway license to operate. A future enhancement could be to allow changing of the environment variables to target a different location and a generic username and password for authentication.

**Note**: With `freemium` (using Kong Gateway without a license) a custom plugin can still be used; however advanced enterprise features may be unavailable which might not be a problem for most plugins.

2021-05-28 12:21 UTC, mikefero commented on pongo.sh
> +  KONG_EE_PRIVATE_TAG_FALLBACK_POSTFIX="-alpine"
> Not sure this is correct? kong/kong-gateway-private is the repo for non-public Enterprise images, eg. 0.36-2

I am a little confused here, for Enterprise we want to make the fallback be the private Docker Hub repository (e.g. older releases and releases that have not been byte compiled and made publicly available) so a KONG_VERSION can be retrieved from the proper Docker Hub repository (e.g. `kong/kong-gateway` or `kong/kong-gateway-private`).

> This whole problem does not exist for EE afaik, so this should not be FALLBACK.

Is it just the naming of the variable?

2021-05-29 11:37 UTC, Tieske commented on pongo.sh
> +  KONG_EE_PRIVATE_TAG_FALLBACK_POSTFIX="-alpine"
It's just naming indeed. The OSS one should have "UNOFFICIAL" probably, and the EE one "PRIVATE", instead of "FALLBACK", that would better cover their uses.

2021-05-29 12:36 UTC, aboudreault commented on pongo.sh
> +  KONG_EE_PRIVATE_TAG_FALLBACK_POSTFIX="-alpine"
alright. I will do the renaming.

2021-06-02 13:04 UTC, aboudreault commented
@mikefero @Tieske I'm trying to get some info about the best way to communicate this change to customers, since that some are using the repo in their pipeline. We'll take care to update the ee plugins, but do you know if there is someone on the core team that could help for the core ones?

2021-06-02 13:45 UTC, mikefero approved these changes
Nice work @aboudreault ... this looks great!

> but do you know if there is someone on the core team that could help for the core ones?

@gszr would be a good POC for this.

2021-06-02 13:45 UTC, mikefero commented on pongo.sh
> +  NIGHTLY_EE_TAG="kong/kong-gateway-internal:master-nightly-alpine"
Out of scope for this PR, but it will be nice in the future to be able to specify nightly image since we have multiple active nightlies.

2021-06-02 13:46 UTC, aboudreault commented on pongo.sh
> +  NIGHTLY_EE_TAG="kong/kong-gateway-internal:master-nightly-alpine"
+1, let's keep track of those improvement in GH issues.

2021-06-07 14:52 UTC, merged