[WIP] Add 3.0 EE versionning support
Kong/kong-pongo pull request #286
Opened 2022-05-31 16:17 UTC by aboudreault

@Tieske this is a quick try to support the 3 digit EE versioning.. I do not especially like to use another globally shared variable but works well.

2022-06-02 06:44 UTC, Tieske requested changes
approach looks good. One question: the new `--ee` or `--enterprise` flag is required, even if you specify a 4 digit version right? That would be a breaking change, and should not be required. It should auto-detect  the old Enterprise versions.

So if no `--ee` is given, and the version is not found as a CE one, it should search for an EE one automatically, and set the internal global flag for EE.

2022-06-02 06:44 UTC, Tieske commented on assets/set_variables.sh
> +    if [[ "$IS_ENTERPRISE" == "true" ]]; then
```suggestion
    local available_versions
    if [[ "$IS_ENTERPRISE" == "true" ]]; then
```

2022-06-02 06:44 UTC, Tieske commented on assets/set_variables.sh
> +  if [[ "$IS_ENTERPRISE" == "true" ]] && [[ -d "$LOCAL_PATH/kong-versions/${version}-ee/kong" ]]; then
the `-d` check is not necessary here? if the version is valid, the files must exist.

2022-06-02 06:44 UTC, Tieske commented on assets/set_variables.sh
> +  if [[ "$IS_ENTERPRISE" == "true" ]] && [[ -d "$LOCAL_PATH/kong-versions/${version}-ee/kong" ]]; then
the `-d` check is not necessary here? if the version is valid, the files must exist.

2022-06-02 12:03 UTC, aboudreault reviewed
@Tieske the --enterprise flag is only required when running pongo with a version >=3. so something like: `KONG_VERSION=3.0.0 pongo run --enterprise`. Otherwise, it will work as before.

2022-06-02 12:03 UTC, aboudreault commented on assets/set_variables.sh
> +  if [[ "$IS_ENTERPRISE" == "true" ]] && [[ -d "$LOCAL_PATH/kong-versions/${version}-ee/kong" ]]; then
I added the -d check because it is possible to also specified `--enterprise` with older versions, so we need it to resolve to the old asset path.

2022-06-03 08:38 UTC, Tieske commented
something is really wrong with the Github UI here, duplicates of message

with regard to the `-d` check:

> I added the -d check because it is possible to also specify `--enterprise` with older versions, so we need it to resolve to the old asset path.

I see. In that case please know that the update script will recreate ALL Kong version data. If we update that one to include/append `-ee` to all EE versions, then also all older versions/paths would be updated. And we can forego on these additional checks anyway. That would be cleaner I think?

2022-06-06 12:53 UTC, aboudreault commented
@Tieske that's exactly what I noticed while working on the add/update scripts. and yes, adding `-ee` to all enterprise versions make sense. I thought only the new version assets would be added using that script. :+1:

2022-06-07 17:38 UTC, aboudreault commented
@Tieske I tried a different approach with my latest changes. Internally, pongo is now supporting this version format `x.y.z[.w][-ee]`.

Note that I also updated  all artifacts and the github UI doesn't seem to like that...

2022-06-07 19:14 UTC, aboudreault commented
I've drop the commit that updates all the artifacts because I am unable to load the diff page to review. Here is the real CI run: https://app.travis-ci.com/github/Kong/kong-pongo/builds/251653402

2022-06-07 19:15 UTC, aboudreault commented on assets/set_variables.sh
> +  if [[ "${VERSION_INFO[1]}" == "ee" ]]; then
use `-1`

2022-06-07 19:16 UTC, aboudreault commented on assets/update_versions.sh
> +            repo_url=https://$token:@github.com/aboudreault/$repo_name.git
of course will be reverted

2022-06-14 22:12 UTC, tyler-ball approved these changes

2022-06-20 09:15 UTC, Tieske commented
this has become a complex change. I think we'd be better of to include a simple`e` prefix to the version. eg. `1.2.3` for CE, `e1.2.3` for EE.

This will also make it easier in CI, since we'd need a single parameter in CI matrices, where otherwise we'd need 2; the version and the flag.

2022-06-20 10:37 UTC, Tieske commented
Created #291 as a simpler version. Just need a way to test it.

2022-06-20 11:49 UTC, aboudreault commented
@Tieske I am OK if you want to go your direction for this feature, but note that we will need to merge a functional one as soon as we bump the version to 3.0.0. I tested mine with a fork of the CE and EE repos with a new 3.0.0 tag pushed in both. It also supports reading the version from a kong image.

2022-07-06 12:53 UTC, closed without merging