fix(mount) update permissions to ensure access
Kong/kong-pongo pull request #321
Opened 2022-09-13 07:08 UTC by Tieske

Modify the 'kong' user to match the ownership of the mounted plugin folder. Kong will not start because of permission errors if it cannot write to the /kong-plugin/servroot folder (which resides on the mount). Since those permissions are controlled by the host, we update the 'kong' user inside the container to match the UID and GID.

2022-09-13 07:39 UTC, hanshuebner requested changes

2022-09-13 07:39 UTC, hanshuebner commented on assets/pongo_entrypoint.sh
> +# inside the container to match the UID and GID.
There is a slight chance that `MOUNT_UID` or `MOUNT_GID` will match an existing UID or GID in the container.  That will cause `usermod` and `groupmod` below to fail.  I would rather not redirect the diagnostic of `groupmod` and `usermod` so that if this rare case occurs, one at least sees that there was a problem.

2022-09-13 08:32 UTC, Tieske commented on assets/pongo_entrypoint.sh
> +# inside the container to match the UID and GID.
I had that, on my system;
```
[Kong-2.8.1:tmp:/kong]$ /kong-plugin/try.sh
+ id -u kong
+ KONG_UID=100
+ id -g kong
+ KONG_GID=65533
+ stat -c '%u' /kong-plugin
+ MOUNT_UID=0
+ stat -c '%g' /kong-plugin
+ MOUNT_GID=0
+ '[' '!' 65533 '=' 0 ]
+ groupmod -g 0 kong
groupmod: GID '0' already exists
+ '[' '!' 100 '=' 0 ]
+ usermod -u 0 -g 0 kong
usermod: UID '0' already exists
```
and hence I disabled the output, because I expect this to be the common case actually. That said, if you have a better alternative, that would be great.

2022-09-13 08:50 UTC, hanshuebner commented on assets/pongo_entrypoint.sh
> +# inside the container to match the UID and GID.
From what I can see, the "already exists" message indicates that the operation was not successful:
```
hans-release-host 1049_% docker run -it ubuntu:latest bash
root@6d48c9cd4db9:/# grep daemon /etc/passwd
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
root@6d48c9cd4db9:/# usermod -u 0 -g 0 daemon
usermod: UID '0' already exists
root@6d48c9cd4db9:/# grep daemon /etc/passwd
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
```
The `--non-unique` flag allows the specification of non-unique IDs:
```
root@6d48c9cd4db9:/# usermod --non-unique -u 0 -g 0 daemon
root@6d48c9cd4db9:/# grep daemon /etc/passwd
daemon:x:0:0:daemon:/usr/sbin:/usr/sbin/nologin
```
By setting the uid to 0, the account effectively becomes a root account itself.

Summing up:  I think the `--non-unique` flag is required so that the mechanism works even when the plugin directory is owned by root, which you say is the common case.

2022-09-13 10:18 UTC, Tieske commented on assets/pongo_entrypoint.sh
> +# inside the container to match the UID and GID.
Alternative: using the `z` option, see https://stackoverflow.com/a/35222815/746559 wdyt @hanshuebner ?

But would need to test with @gAmUssA whether that also solves the issue.

2022-09-13 10:33 UTC, Tieske commented on assets/pongo_entrypoint.sh
> +# inside the container to match the UID and GID.
@hanshuebner added new commit with `--non-unique` and stop dismissing output

2022-09-13 10:43 UTC, hanshuebner commented on assets/pongo_entrypoint.sh
> +# inside the container to match the UID and GID.
From reading the post, it does not appear that the `-z` flag changes the file permissions or ownership.  Rather, it seems to control how SELinux deals with the mount.  What'd be needed instead would be a way to map from in-container user ids to host user ids for file system access.  Docker does not support that, and neither does the Linux kernel itself at this point, so I guess your idea of changing the container user ID to match the plugin file owner is sound.

Another option would be to always run the pongo shell as root instead of creating a pongo user.  With the current solution, this is effectively what will happen if the plugin files are owned by root.  The downside of running is that it is an atypical run mode and may cause developers to assume that the plugin has privileges which it does not have in real deployments.

2022-09-13 10:43 UTC, hanshuebner approved these changes

2022-09-13 13:37 UTC, merged

2022-09-13 14:17 UTC, Tieske commented on assets/pongo_entrypoint.sh
> +# inside the container to match the UID and GID.
The change in ID's is the `kong` user, used when starting Kong, for the worker processes. The shell already runs as root.

2022-09-13 15:46 UTC, gAmUssA commented
My permission error went away, but I've got another error

```
Declarative file "kong.yml/yaml/json" not found, skipping import
Error: nginx configuration is invalid (exit code 1):
nginx: the configuration file /kong-plugin/servroot/nginx.conf syntax is ok
nginx: [emerg] bind() to unix:/kong-plugin/servroot/worker_events.sock failed (1: Operation not permitted)
nginx: configuration file /kong-plugin/servroot/nginx.conf test failed
```

Does anyone see it?

Thank you

2022-12-12 22:48 UTC, dcominottim commented
> My permission error went away, but I've got another error
> 
> ```
> Declarative file "kong.yml/yaml/json" not found, skipping import
> Error: nginx configuration is invalid (exit code 1):
> nginx: the configuration file /kong-plugin/servroot/nginx.conf syntax is ok
> nginx: [emerg] bind() to unix:/kong-plugin/servroot/worker_events.sock failed (1: Operation not permitted)
> nginx: configuration file /kong-plugin/servroot/nginx.conf test failed
> ```
> 
> Does anyone see it?
> 
> Thank you

I am getting the same error with pongo 2.2.0 while trying to test https://github.com/Kong/kong-plugin. I am running inside of WSL2.