Add support to globally disable health checks for dependencies
Kong/kong-pongo pull request #404
Opened 2023-06-05 14:30 UTC by onmomo

We ran into an issue on our system with the predefined health checks never pass since our dockerized CI (Kubernetes / rootless Podman build agent) does not support running systemd and therefore containers are never turning into "healthy" state. Basically, [this script](https://github.com/Kong/kong-pongo/blob/57259bfaab5da2d4d080808d10d6182dbb6b34a0/pongo.sh#L647) hangs forever if docker inspect returns "Health": {} that never turn into state `healthy` (in our case it will stay in state `starting`)

As a workaround, we managed to add a custom local dependency that overwrites the predefined health checks.
```
cat .pongo/service.yml

  postgres:
    healthcheck:
      disable: true # disable kong postgres health check since our CI does not support healthy state that requires systemd
```
This PR introduces an additional ENV variable `SERVICE_DISABLE_HEALTHCHECK` to disable the built in kongo dependency health checks.

2023-06-06 09:32 UTC, Tieske commented
@onmomo in the `healthy` function it's probably easier to check for the env var and if `true` simply return a `0`. No need to fiddle with the docker checks themselves there.

2023-06-06 09:35 UTC, Tieske reviewed
can you add a section to the readme, eg [here](https://github.com/Kong/kong-pongo/blob/master/README.md?plain=1#L353) to explain the feature?

2023-06-06 09:37 UTC, Tieske commented on assets/help/up.txt
> +  SERVICE_DISABLE_HEALTHCHECK set true to disable dependency health checks globally
```suggestion
  SERVICE_DISABLE_HEALTHCHECK
                   set true to disable dependency health checks globally
```

2023-06-07 10:49 UTC, Tieske requested changes
I have some doubts on the wait time. Becasue we only want to wait when we do an "automatic" enviornment start before a test run. Not when doing a `pongo up`, and also not when doing `pongo run` whilst the environment was already started.

So maybe we should skip the wait alltogether, and then the user can manually do `pongo up && sleep xxx && pongo run`, or just `pongo run` if the environment is already up.

2023-06-07 10:49 UTC, Tieske commented on README.md
> +Furthermore, if health checks are disabled the `pongo.sh` will wait 5 seconds for any dependency to become healthy. This can be adjusted setting the environment variable `SERVICE_DISABLE_HEALTHCHECK_
if we're introducing a second variable, can't we then use only the second? if not set, we use health checks, if set, we disable health checks and wait for the number of seconds specified.

wdyt?

2023-06-07 10:49 UTC, Tieske commented on README.md
> +When unable to leverage container health checks, they can be disabled setting the environment variable `SERVICE_DISABLE_HEALTHCHECK=true`
missing empty line after the heading

2023-06-07 10:49 UTC, Tieske commented on pongo.sh
> +      sleep "$wait"
instead of sleeping per container, can't we sleep once for the whole lot of them? eg. Cassandra can take 15 to 30 seconds. So setting it to 30, means that if we also have Postgres and Redis, the total time becomes 1.5 minute.

2023-06-07 13:03 UTC, onmomo commented on pongo.sh
> +      sleep "$wait"
yes, this is indeed not very nice. I removed now the sleep and leave it up to the client to decided on the sleep as you suggested. Only disadvantage I see with this approach is, if the service requires a dependency up and running without the `restart: on-failure` in kong-pongo docker-compose configured. But I think we can ignore this since currently this flag is set everywhere and one could still overwrite the services in a custom local dependency.

2023-06-07 13:03 UTC, onmomo commented on README.md
> +When unable to leverage container health checks, they can be disabled setting the environment variable `SERVICE_DISABLE_HEALTHCHECK=true`
done

2023-06-07 13:03 UTC, onmomo commented on README.md
> +Furthermore, if health checks are disabled the `pongo.sh` will wait 5 seconds for any dependency to become healthy. This can be adjusted setting the environment variable `SERVICE_DISABLE_HEALTHCHECK_
I removed the wait variable completely

2023-06-13 08:41 UTC, closed without merging