fix(*) only mount logs directory and use a different prefix
Kong/kong-pongo pull request #474
Opened 2023-11-24 07:31 UTC by fffonion

2023-11-24 08:52 UTC, Tieske commented
where are the unix sockets currently located? At the top of the `prefix`?

2023-11-24 09:09 UTC, Tieske reviewed
Am I correct we loose access to everything but the logs? eg. no way to inspect the generated nginx config files from the host?

2023-11-24 09:09 UTC, Tieske commented on assets/docker-compose.yml
> +      - ${PONGO_WD}/servroot/logs:/kong-prefix
Isn't this missing the "logs" part?
```suggestion
      - ${PONGO_WD}/servroot/logs:/kong-prefix/logs
```

2023-11-24 09:09 UTC, Tieske commented on assets/docker-compose.yml
> +      - ${PONGO_WD}/servroot/logs:/kong-prefix
will this work if `${PONGO_WD}/servroot/logs` doesn't exist?

2023-11-24 09:26 UTC, fffonion commented on assets/docker-compose.yml
> +      - ${PONGO_WD}/servroot/logs:/kong-prefix
> will this work if ${PONGO_WD}/servroot/logs doesn't exist?
yes, docker by default create missing paths as directory, which is what we want

2023-11-24 09:29 UTC, fffonion commented
> where are the unix sockets currently located? At the top of the prefix?

yes

> Am I correct we loose access to everything but the logs? eg. no way to inspect the generated nginx config files from the host?

yes, others are not being re-mounted or symlinked in this PR. As from the comments that logs are the reason we use prefix from mount at first place, so that is being implemented here as first iterration.

2023-11-24 09:39 UTC, fffonion commented on assets/docker-compose.yml
> +      - ${PONGO_WD}/servroot/logs:/kong-prefix
> Isn't this missing the "logs" part?

you are right, applied

2023-12-05 11:33 UTC, Tieske requested changes
somehow I still see the files appear on the mount.

2023-12-05 11:33 UTC, Tieske commented on pongo.sh
> +    warn "pongo container and inspect \$KONG_PREFIX directory"
Can we skip this warning? it now shows on every pongo command there is. Which is noise. Let's just remove it and see what happens.

2023-12-05 11:41 UTC, Tieske commented
> somehow I still see the files appear on the mount.

That's because I used the old containers. `pongo nuke` to remove all of them solved it.

2023-12-06 07:07 UTC, fffonion commented on pongo.sh
> +    warn "pongo container and inspect \$KONG_PREFIX directory"
removed

2023-12-13 07:50 UTC, outsinre approved these changes

2023-12-13 07:50 UTC, outsinre commented on assets/docker-compose-linux-extend.yml
> +      - ${PONGO_WD}/servroot:/kong-prefix
Conflicts with https://github.com/Kong/kong-pongo/blob/master/assets/docker-compose.yml#L171-L172?

2023-12-13 16:47 UTC, Tieske commented on assets/docker-compose-linux-extend.yml
> +      - ${PONGO_WD}/servroot:/kong-prefix
@fffonion mind having a look? I think we can remove the one from the main docker compose file no?

2023-12-14 06:27 UTC, fffonion commented on assets/docker-compose-linux-extend.yml
> +      - ${PONGO_WD}/servroot:/kong-prefix
actually no conflict here, the mount from main file is for getting in the plugin code for test.

2023-12-14 06:29 UTC, fffonion commented on assets/docker-compose-linux-extend.yml
> +      - ${PONGO_WD}/servroot:/kong-prefix
pwd -> /kong-plugin
pwd/servroot -> /kong-prefix
we can't do
pwd/servroot -> /kong-plugin/servroot
anymore because that will be a bind mount on host and not supported on macos

2023-12-14 07:25 UTC, outsinre approved these changes

2023-12-14 08:45 UTC, Tieske commented
@fffonion can you squash the commits first, and then merge (squashing via ui is disabled)

2023-12-14 08:46 UTC, Tieske commented
nvm I'll do it

2023-12-14 08:46 UTC, fffonion commented
Thank you @Tieske

2023-12-14 08:47 UTC, merged

2023-12-14 08:53 UTC, outsinre commented
It is merged, but we can look at https://stackoverflow.com/a/66047856.

It can exclude a specific file when mounting.