fix(*): wait_for_dependency will wait forever for unhealthy container
Kong/kong-pongo pull request #551
Opened 2024-04-08 09:34 UTC by StarlightIbuki

As the title says.

2024-04-08 09:35 UTC, Tieske commented on pongo.sh
> +  state=$(docker inspect "$iid" | jq .[0].State.Health.Status)
please do not introduce more dependencies, even if it's `jq`

2024-04-08 09:46 UTC, StarlightIbuki commented on pongo.sh
> +  state=$(docker inspect "$iid" | jq .[0].State.Health.Status)
Rewritten.

2024-04-09 08:00 UTC, Tieske commented on pongo.sh
> +  state=$(docker inspect --format='{{.State.Health.Status}}' "$iid")
I'm hesitant with these types of changes, on how we validate status and how we collect that input. We've had plenty of issues in the past due to different Docker versions, or even non-Docket tools being used.

So are these changes necessary?

2024-04-09 08:44 UTC, StarlightIbuki commented on pongo.sh
> +  state=$(docker inspect --format='{{.State.Health.Status}}' "$iid")
The runner blocks until it times out when a container fails to start, and it gives no reason. This makes it hard to diagnose issues with container setup. I'm trying to improve the situation.

2024-04-09 08:48 UTC, StarlightIbuki commented on pongo.sh
> +  state=$(docker inspect --format='{{.State.Health.Status}}' "$iid")
I can find a use of this in a 7 years ago script: https://github.com/jordyv/wait-for-healthy-container/blob/master/wait-for-healthy-container.sh, so maybe we can consider it a stable interface.

2024-04-15 11:13 UTC, Tieske commented on pongo.sh
> +  state=$(docker inspect --format='{{.State.Health.Status}}' "$iid")
@StarlightIbuki don't get me wrong, I like the improvements, but what I'm hesitant about is changing the checks themselves as you do in the above lines.

2024-04-15 11:23 UTC, Tieske requested changes

2024-04-15 11:23 UTC, Tieske commented on pongo.sh
> +function status {
Can you add comments here specifically what the returned values are?

Then I think there are issues here, it can return `0` for success (for example if health checks are disabled). Yet in the calling code, that is not checked, since it only checks "healthy" as return value.

So I think this currently breaks the "SERVICE_DISABLE_HEALTHCHECK" option

2024-04-15 11:23 UTC, Tieske commented on pongo.sh
> +  while [ "$(status "$iid" "$dep")" == "starting" ]; do
should we bail out of this loop after a timeout period? eg. 60 seconds?

2024-04-16 07:55 UTC, StarlightIbuki commented on pongo.sh
> +  while [ "$(status "$iid" "$dep")" == "starting" ]; do
That makes sense. I was blindly following the original behavior.

2024-04-17 12:54 UTC, Tieske commented
@StarlightIbuki see #554 for an alternative implementation

2024-04-19 06:37 UTC, closed without merging