release 2.11.0
Kong/kong-pongo pull request #561
Opened 2024-05-29 16:06 UTC by locao

2024-05-29 17:45 UTC, kikito approved these changes

2024-05-30 08:26 UTC, Tieske requested changes

2024-05-30 08:26 UTC, Tieske commented on CHANGELOG.md
> +* Feat: Kong OSS 3.7.0
3.7.0 is in here twice, intentional? or was there another one?

2024-05-30 08:26 UTC, Tieske commented on CHANGELOG.md
> +* Feat: Kong OSS 3.7.0
also, can we reverse the order here, in line with older changelog entries? eg. 3.7 at the top, 2.8 at the bottom

2024-05-30 10:33 UTC, merged