feat: add custom ca certificate support for pongo image
Kong/kong-pongo pull request #632
Opened 2024-10-30 13:19 UTC by tysoekong

This allows pongo to add a custom CA into the container image's OS truststore during the build/up.

It allows the user to add e.g. their employer's traffic inspection CA.

It makes these all works, when running behind e.g. Zscaler:

* Kong outbound requests
* pip3
* luarocks
* git
* probably everything else

2024-10-30 13:21 UTC, tysoekong commented
Oh it's failing all code coverage also

2024-11-05 16:00 UTC, Tieske requested changes

2024-11-05 16:00 UTC, Tieske commented on README.md
> +
Since this is added in the container build, I think this should go in the help-docs of the `pongo build` command.

2024-11-05 16:00 UTC, Tieske commented on README.md
> +$ PONGO_CUSTOM_CA_CERT="$(pwd)/zscaler-root.crt" pongo up
this is a bad example I think, though it would probably work if the container image still needs to be build.
So I think the example should have 2 commands;

1. the build command including the flag for CA certs
2. the run command without the flags (to indicate clearly they are in the image)

2024-11-05 16:00 UTC, Tieske commented on pongo.sh
> +    echo -n '' > "$LOCAL_PATH/custom_ca.crt"
can't we add it in some less visisble location?

2024-11-05 16:01 UTC, Tieske commented
@tysoekong wdyt; should the cert be added in the build stage (and become part of the created image), or should it be added while doing a pongo run/shell? (eg. upon container instantiation)

2025-07-08 10:45 UTC, kikito commented
Closed by https://github.com/Kong/kong-pongo/pull/671

2025-07-08 10:45 UTC, closed without merging